package com.drawpin.domain.entity;

import com.drawpin.domain.enums.CreatorVerificationStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity representing a Creator profile on the platform.
 *
 * <p>This entity acts as a One-to-One extension of the {@link User} entity.
 * It contains creator-specific metadata, verification statuses, and aggregated stats
 * (followers, artworks, reviews) ensuring the core `users` table remains lightweight.
 *
 * <p><b>Table:</b> {@code creators}<br>
 * <b>Managed by Flyway:</b> {@code V4__create_creator_profile.sql}
 *
 * <p><b>Connected to:</b>
 * <ul>
 *   <li>{@link User} — one-to-one mapping representing the root identity</li>
 * </ul>
 */
@Entity
@Table(name = "creators")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Creator {

    /** Surrogate UUID primary key. Generated by PostgreSQL's {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * The root user identity. 
     * Mapped as OneToOne with lazy loading to prevent N+1 issues.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true, updatable = false)
    private User user;

    /** Display name specifically for the creator persona. */
    @Column(name = "display_name", nullable = false, length = 80)
    private String displayName;

    /** Bio specifically for the creator portfolio. Max 500 chars. */
    @Column(name = "bio", length = 500)
    private String bio;

    /** Main specialization (e.g., '3D Animator', 'Illustrator'). */
    @Column(name = "specialization", length = 100)
    private String specialization;

    /** Years of professional experience. */
    @Column(name = "experience_years")
    @Builder.Default
    private Integer experienceYears = 0;

    /** JSONB array of skill tags. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "skills")
    private List<String> skills;

    /** Personal portfolio website. */
    @Column(name = "portfolio_website", length = 255)
    private String portfolioWebsite;

    /** JSONB object storing social media links (e.g., twitter, instagram, dribbble). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "social_links")
    private Map<String, String> socialLinks;

    /** Whether the creator is currently available for freelance/orders. */
    @Column(name = "is_available", nullable = false)
    @Builder.Default
    private boolean isAvailable = true;

    /** Admin verification status. */
    @Enumerated(EnumType.STRING)
    @Column(name = "verification_status", nullable = false, length = 20)
    @Builder.Default
    private CreatorVerificationStatus verificationStatus = CreatorVerificationStatus.NONE;

    // --- Statistics (Denormalized for read performance) ---

    @Column(name = "followers_count", nullable = false)
    @Builder.Default
    private int followersCount = 0;

    @Column(name = "following_count", nullable = false)
    @Builder.Default
    private int followingCount = 0;

    @Column(name = "artworks_count", nullable = false)
    @Builder.Default
    private int artworksCount = 0;

    @Column(name = "reviews_count", nullable = false)
    @Builder.Default
    private int reviewsCount = 0;

    @Column(name = "average_rating", nullable = false)
    @Builder.Default
    private double averageRating = 0.0;

    // --- Auditing ---

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
