package com.drawpin.domain.entity;

import com.drawpin.domain.enums.UserRole;
import com.drawpin.domain.enums.UserStatus;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a platform user.
 *
 * <p>This is the root identity entity. Every person on the DrawPin platform — whether a
 * collector, creator, moderator, or admin — is stored in this table. Role-specific
 * extended data (e.g., creator portfolio metadata) lives in the {@link Creator} entity
 * linked by a one-to-one relationship.
 *
 * <p><b>Table:</b> {@code users}<br>
 * <b>Managed by Flyway:</b> {@code V1__create_users.sql}
 *
 * <p><b>Connected to:</b>
 * <ul>
 *   <li>{@link UserSettings} — one-to-one, auto-created on registration</li>
 *   <li>{@link RefreshToken} — one-to-many, one per active device session</li>
 *   <li>{@link PasswordResetToken} — one-to-many, for forgot-password flows</li>
 *   <li>{@link EmailVerification} — one-to-many, for email confirmation</li>
 *   <li>{@link com.drawpin.security.DrawPinUserDetails} — wraps this entity for Spring Security</li>
 * </ul>
 *
 * <p><b>Frontend APIs that consume this entity (via DTOs):</b>
 * <ul>
 *   <li>{@code POST /api/v1/auth/register}</li>
 *   <li>{@code POST /api/v1/auth/login}</li>
 *   <li>{@code GET /api/v1/users/me}</li>
 * </ul>
 */
@Entity
@Table(name = "users")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Surrogate UUID primary key. Generated by PostgreSQL's {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** Unique email address. Used as the login identifier. */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /** Email address waiting to be verified before replacing the primary email. */
    @Column(name = "pending_email", length = 255)
    private String pendingEmail;

    /** BCrypt-hashed password. Never stored or returned in plain text. */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /** Public display name. Shown across the platform. */
    @Column(name = "name", nullable = false, length = 80)
    private String name;

    /** Unique URL-safe username (e.g., {@code aria.vance}). */
    @Column(name = "handle", nullable = false, unique = true, length = 40)
    private String handle;

    /** Cloudinary URL for the user's avatar image. Nullable until uploaded. */
    @Column(name = "avatar_url")
    private String avatarUrl;

    /** Cloudinary URL for the user's profile cover banner. Nullable until uploaded. */
    @Column(name = "cover_url")
    private String coverUrl;

    /** Short bio displayed on the profile page. Max 300 characters. */
    @Column(name = "bio", length = 300)
    private String bio;

    /** City or location string displayed on profile. */
    @Column(name = "city", length = 80)
    private String city;

    /** Personal website URL. Optional. */
    @Column(name = "website", length = 255)
    private String website;

    /**
     * Platform role determining what the user can do.
     * Stored as a string ({@code ENUM_VALUE}) in the DB.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    @Builder.Default
    private UserRole role = UserRole.COLLECTOR;

    /** Account lifecycle status. Checked on every login attempt. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private UserStatus status = UserStatus.ACTIVE;

    /** Whether this user has been manually verified by an admin. */
    @Column(name = "is_verified", nullable = false)
    @Builder.Default
    private boolean isVerified = false;

    /** Whether the user has confirmed their email via the verification email. */
    @Column(name = "email_verified", nullable = false)
    @Builder.Default
    private boolean emailVerified = false;

    /**
     * Number of consecutive failed login attempts.
     * Resets to 0 on successful login.
     * Triggers account lockout when it reaches the configured threshold (default: 5).
     */
    @Column(name = "failed_login_count", nullable = false)
    @Builder.Default
    private int failedLoginCount = 0;

    /**
     * Timestamp until which this account is locked due to excessive failed login attempts.
     * Null when the account is not locked.
     */
    @Column(name = "locked_until")
    private Instant lockedUntil;

    /** Auto-populated by Spring Data JPA auditing on entity creation. */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Auto-populated by Spring Data JPA auditing on every entity update. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Soft-delete timestamp. When set, the account is considered deleted. */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    // ─────────────────────────────────────────────────────────────────────────
    // DOMAIN HELPERS
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Returns {@code true} if this account is currently locked due to too many
     * failed login attempts.
     *
     * @return {@code true} if {@code lockedUntil} is in the future
     */
    public boolean isAccountLocked() {
        return lockedUntil != null && Instant.now().isBefore(lockedUntil);
    }

    /**
     * Returns {@code true} if this account has been soft-deleted.
     *
     * @return {@code true} if {@code deletedAt} is non-null
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }
}
