package com.drawpin.util;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * Utility class for producing SHA-256 hashes of sensitive string tokens.
 *
 * <p>Raw tokens generated by {@link TokenUtils} are always hashed before
 * being stored in the database. This means even if the database is compromised,
 * the raw tokens (and therefore the actual cookies/links) remain secret.
 *
 * <p>On validation, the submitted raw token is re-hashed with this same method
 * and compared against the stored hash — no decryption is ever needed or possible.
 *
 * <p>This is a stateless utility class. All methods are static.
 */
public final class HashUtils {

    private HashUtils() {
        // Utility class — not instantiable
    }

    /**
     * Computes the SHA-256 hash of the given input string and returns it as a
     * lowercase hexadecimal string (64 characters).
     *
     * @param input the raw token string to hash (must not be null)
     * @return 64-character lowercase hex SHA-256 digest
     * @throws IllegalStateException if SHA-256 algorithm is unavailable (should never happen on JVM)
     */
    public static String sha256(String input) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hashBytes);
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is mandated by the Java platform spec — this is unreachable in practice
            throw new IllegalStateException("SHA-256 algorithm not available on this JVM", e);
        }
    }
}
