package com.drawpin.mapper;

import com.drawpin.domain.entity.Media;
import com.drawpin.dto.response.media.MediaMetadataResponse;
import com.drawpin.dto.response.media.MediaResponse;
import com.drawpin.dto.response.media.MediaUploadResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.Map;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface MediaMapper {

    MediaUploadResponse toUploadResponse(Media media);

    @Mapping(target = "variants", expression = "java(generateVariants(media))")
    MediaResponse toResponse(Media media);

    MediaMetadataResponse toMetadataResponse(Media media);
    
    default Map<String, String> generateVariants(Media media) {
        if (media == null || media.getSecureUrl() == null) {
            return Map.of();
        }
        
        // As a foundation, if we are using Cloudinary, the URL structure usually 
        // includes /upload/. We can inject transformations. But since we need 
        // to stay agnostic in the Mapper, we rely on the URL generated by the StorageService.
        // For now, variants can just be placeholders or empty unless explicitly 
        // resolved by the service layer later.
        
        // Future proofing: variants will be populated by the Service layer if needed,
        // or we return an empty map here to satisfy the DTO contract without 
        // leaking Cloudinary logic into MapStruct.
        return Map.of("original", media.getSecureUrl());
    }
}
