/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioManagerRouteImport } from './routes/portfolio-manager'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DiscoverMapRouteImport } from './routes/discover-map'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateServiceRouteImport } from './routes/create-service'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R500RouteImport } from './routes/500'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceServiceIdRouteImport } from './routes/service.$serviceId'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PinPinIdRouteImport } from './routes/pin.$pinId'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as MessagesChatIdRouteImport } from './routes/messages.$chatId'
import { Route as EditServiceServiceIdRouteImport } from './routes/edit-service.$serviceId'
import { Route as CreatorCreatorIdRouteImport } from './routes/creator.$creatorId'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as OrderOrderIdTrackingRouteImport } from './routes/order.$orderId.tracking'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioManagerRoute = PortfolioManagerRouteImport.update({
  id: '/portfolio-manager',
  path: '/portfolio-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverMapRoute = DiscoverMapRouteImport.update({
  id: '/discover-map',
  path: '/discover-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateServiceRoute = CreateServiceRouteImport.update({
  id: '/create-service',
  path: '/create-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PinPinIdRoute = PinPinIdRouteImport.update({
  id: '/pin/$pinId',
  path: '/pin/$pinId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => MessagesRoute,
} as any)
const EditServiceServiceIdRoute = EditServiceServiceIdRouteImport.update({
  id: '/edit-service/$serviceId',
  path: '/edit-service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCreatorIdRoute = CreatorCreatorIdRouteImport.update({
  id: '/creator/$creatorId',
  path: '/creator/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const OrderOrderIdTrackingRoute = OrderOrderIdTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => OrderOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/boards': typeof BoardsRoute
  '/checkout': typeof CheckoutRoute
  '/create': typeof CreateRoute
  '/create-service': typeof CreateServiceRoute
  '/dashboard': typeof DashboardRoute
  '/discover-map': typeof DiscoverMapRoute
  '/earnings': typeof EarningsRoute
  '/explore': typeof ExploreRoute
  '/followers': typeof FollowersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/portfolio-manager': typeof PortfolioManagerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/edit-service/$serviceId': typeof EditServiceServiceIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/order/$orderId': typeof OrderOrderIdRouteWithChildren
  '/pin/$pinId': typeof PinPinIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/order/$orderId/tracking': typeof OrderOrderIdTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/boards': typeof BoardsRoute
  '/checkout': typeof CheckoutRoute
  '/create': typeof CreateRoute
  '/create-service': typeof CreateServiceRoute
  '/dashboard': typeof DashboardRoute
  '/discover-map': typeof DiscoverMapRoute
  '/earnings': typeof EarningsRoute
  '/explore': typeof ExploreRoute
  '/followers': typeof FollowersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/portfolio-manager': typeof PortfolioManagerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/edit-service/$serviceId': typeof EditServiceServiceIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/order/$orderId': typeof OrderOrderIdRouteWithChildren
  '/pin/$pinId': typeof PinPinIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/order/$orderId/tracking': typeof OrderOrderIdTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/boards': typeof BoardsRoute
  '/checkout': typeof CheckoutRoute
  '/create': typeof CreateRoute
  '/create-service': typeof CreateServiceRoute
  '/dashboard': typeof DashboardRoute
  '/discover-map': typeof DiscoverMapRoute
  '/earnings': typeof EarningsRoute
  '/explore': typeof ExploreRoute
  '/followers': typeof FollowersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/portfolio-manager': typeof PortfolioManagerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/edit-service/$serviceId': typeof EditServiceServiceIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/order/$orderId': typeof OrderOrderIdRouteWithChildren
  '/pin/$pinId': typeof PinPinIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/order/$orderId/tracking': typeof OrderOrderIdTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/admin'
    | '/analytics'
    | '/boards'
    | '/checkout'
    | '/create'
    | '/create-service'
    | '/dashboard'
    | '/discover-map'
    | '/earnings'
    | '/explore'
    | '/followers'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/order-confirmation'
    | '/orders'
    | '/payment'
    | '/portfolio-manager'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/users'
    | '/board/$boardId'
    | '/creator/$creatorId'
    | '/edit-service/$serviceId'
    | '/messages/$chatId'
    | '/order/$orderId'
    | '/pin/$pinId'
    | '/profile/edit'
    | '/service/$serviceId'
    | '/order/$orderId/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/admin'
    | '/analytics'
    | '/boards'
    | '/checkout'
    | '/create'
    | '/create-service'
    | '/dashboard'
    | '/discover-map'
    | '/earnings'
    | '/explore'
    | '/followers'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/order-confirmation'
    | '/orders'
    | '/payment'
    | '/portfolio-manager'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/users'
    | '/board/$boardId'
    | '/creator/$creatorId'
    | '/edit-service/$serviceId'
    | '/messages/$chatId'
    | '/order/$orderId'
    | '/pin/$pinId'
    | '/profile/edit'
    | '/service/$serviceId'
    | '/order/$orderId/tracking'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/admin'
    | '/analytics'
    | '/boards'
    | '/checkout'
    | '/create'
    | '/create-service'
    | '/dashboard'
    | '/discover-map'
    | '/earnings'
    | '/explore'
    | '/followers'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/order-confirmation'
    | '/orders'
    | '/payment'
    | '/portfolio-manager'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/users'
    | '/board/$boardId'
    | '/creator/$creatorId'
    | '/edit-service/$serviceId'
    | '/messages/$chatId'
    | '/order/$orderId'
    | '/pin/$pinId'
    | '/profile/edit'
    | '/service/$serviceId'
    | '/order/$orderId/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  BoardsRoute: typeof BoardsRoute
  CheckoutRoute: typeof CheckoutRoute
  CreateRoute: typeof CreateRoute
  CreateServiceRoute: typeof CreateServiceRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverMapRoute: typeof DiscoverMapRoute
  EarningsRoute: typeof EarningsRoute
  ExploreRoute: typeof ExploreRoute
  FollowersRoute: typeof FollowersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  PortfolioManagerRoute: typeof PortfolioManagerRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  CreatorCreatorIdRoute: typeof CreatorCreatorIdRoute
  EditServiceServiceIdRoute: typeof EditServiceServiceIdRoute
  OrderOrderIdRoute: typeof OrderOrderIdRouteWithChildren
  PinPinIdRoute: typeof PinPinIdRoute
  ServiceServiceIdRoute: typeof ServiceServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-manager': {
      id: '/portfolio-manager'
      path: '/portfolio-manager'
      fullPath: '/portfolio-manager'
      preLoaderRoute: typeof PortfolioManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover-map': {
      id: '/discover-map'
      path: '/discover-map'
      fullPath: '/discover-map'
      preLoaderRoute: typeof DiscoverMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-service': {
      id: '/create-service'
      path: '/create-service'
      fullPath: '/create-service'
      preLoaderRoute: typeof CreateServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/pin/$pinId': {
      id: '/pin/$pinId'
      path: '/pin/$pinId'
      fullPath: '/pin/$pinId'
      preLoaderRoute: typeof PinPinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$chatId': {
      id: '/messages/$chatId'
      path: '/$chatId'
      fullPath: '/messages/$chatId'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/edit-service/$serviceId': {
      id: '/edit-service/$serviceId'
      path: '/edit-service/$serviceId'
      fullPath: '/edit-service/$serviceId'
      preLoaderRoute: typeof EditServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$creatorId': {
      id: '/creator/$creatorId'
      path: '/creator/$creatorId'
      fullPath: '/creator/$creatorId'
      preLoaderRoute: typeof CreatorCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$orderId/tracking': {
      id: '/order/$orderId/tracking'
      path: '/tracking'
      fullPath: '/order/$orderId/tracking'
      preLoaderRoute: typeof OrderOrderIdTrackingRouteImport
      parentRoute: typeof OrderOrderIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MessagesRouteChildren {
  MessagesChatIdRoute: typeof MessagesChatIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesChatIdRoute: MessagesChatIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface OrderOrderIdRouteChildren {
  OrderOrderIdTrackingRoute: typeof OrderOrderIdTrackingRoute
}

const OrderOrderIdRouteChildren: OrderOrderIdRouteChildren = {
  OrderOrderIdTrackingRoute: OrderOrderIdTrackingRoute,
}

const OrderOrderIdRouteWithChildren = OrderOrderIdRoute._addFileChildren(
  OrderOrderIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  BoardsRoute: BoardsRoute,
  CheckoutRoute: CheckoutRoute,
  CreateRoute: CreateRoute,
  CreateServiceRoute: CreateServiceRoute,
  DashboardRoute: DashboardRoute,
  DiscoverMapRoute: DiscoverMapRoute,
  EarningsRoute: EarningsRoute,
  ExploreRoute: ExploreRoute,
  FollowersRoute: FollowersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  PortfolioManagerRoute: PortfolioManagerRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  CreatorCreatorIdRoute: CreatorCreatorIdRoute,
  EditServiceServiceIdRoute: EditServiceServiceIdRoute,
  OrderOrderIdRoute: OrderOrderIdRouteWithChildren,
  PinPinIdRoute: PinPinIdRoute,
  ServiceServiceIdRoute: ServiceServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
